b = {
'common butterfly' : ('90','flying near flowers'),
'yellow butterfly' : ('90','flying near flowers'),
'tiger butterfly' : ('160','flying near flowers'),
'peacock butterfly' : ('220','flying near flowers'),
'monarch butterfly' : ('140','flying near flowers'),
'emperor butterfly' : ('2500','flying near flowers'),
'agrias butterfly' : ('3000','flying near flowers'),
'raja brooke butterfly' : ('2500','flying near river'),
'birdwing butterfly' : ('4000','flying near flowers'),
'moth' : ('60','flying near lights'),
'oak silk moth' : ('1200','on trees'),
'honeybee' : ('100','flying near flowers'),
'bee' : ('2500','in trees'),
'long locust' : ('200','on the ground'),
'migratory locust' : ('600','on the ground'),
'rice grasshopper' : ('400','on the ground'),
'mantis' : ('430','on flowers'),
'orchid mantis' : ('2400','on white flowers'),
'brown cicada' : ('200','on trees'),
'robust cicada' : ('300','on trees'),
'giant cicada' : ('500','on trees'),
'walker cicada' : ('400','on trees'),
'evening cicada' : ('550','on trees'),
'cicada shell' : ('100','on trees'),
'lantern fly' : ('1800','on trees'),
'red dragonfly' : ('80','flying'),
'darner dragonfly' : ('200','flying'),
'banded dragonfly' : ('4500','flying'),
'petaltail dragonfly' : ('8000','flying'),
'ant' : ('80','on rotten food'),
'pondskater' : ('130','swimming on river or pond'),
'diving beetle' : ('800','swimming on river or pond'),
'stinkbug' : ('120','on trees'),
'snail' : ('250','on bushes (rain)'),
'cricket' : ('160','on the ground'),
'bell cricket' : ('430','on the ground'),
'grasshopper' : ('160','on the ground'),
'mole cricket' : ('280','underground'),
'walking leaf' : ('600','on the ground'),
'walking stick' : ('600','on trees'),
'bagworm' : ('300','in trees'),
'ladybug' : ('200','on flowers'),
'violin beetle' : ('260','tree stumps'),
'longhorn beetle' : ('260','tree stumps'),
'tiger beetle' : ('1500','on the ground'),
'dung beetle' : ('800','snow balls'),
'wharf roach' : ('200','on the beach'),
'hermit crab' : ('1000','on the beach'),
'firefly' : ('300','flying near river'),
'fruit beetle' : ('100','on trees'),
'scarab beetle' : ('6000','on trees'),
'jewel beetle' : ('2400','on trees'),
'miyama stag' : ('1000','on trees'),
'saw stag' : ('2000','on trees'),
'giant stag' : ('10000','on trees'),
'rainbow stag' : ('10000','on trees'),
'cyclommatus stag' : ('8000','on palm trees'),
'golden stag' : ('12000','on palm trees'),
'horned dynastid' : ('1350','on trees'),
'horned atlas' : ('8000','on palm trees'),
'horned elephant' : ('8000','on palm trees'),
'horned hercules' : ('12000','on palm '),
'goliath beetle' : ('6000','on palm trees'),
'flea' : ('70','on villagers'),
'pill bug' : ('250','under rocks'),
'mosquito' : ('130','flying'),
'fly' : ('60','flying near trash'),
'house centipede' : ('250','under rocks'),
'centipede' : ('300','under rocks'),
'spider' : ('300','in trees'),
'tarantula' : ('8000','on the ground'),
'scorpion' : ('8000','on the ground')
}